name: Publish on NPM

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setting up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '22'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Lint, typecheck, test and build
        run: pnpm dist

      - name: Publish on NPM
        run: pnpm publish --provenance --no-git-checks
